### ISSUE TITLE
Bachelor Thesis link

### ISSUE THREAD

**Issue by SeanPedersen** [MoritzM00/drcomp#4]
Can not find any link to the mentioned Thesis. Can you provide one?

**Comment by MoritzM00** [comment]
Link: https://github.com/MoritzM00/Bachelor-Thesis/releases/tag/v1.0.7

Unfortunately, the thesis is written in german, which is why I didn‘t link it in this repo‘s Readme.

**Comment by SeanPedersen** [comment]
hey cool, for german readers anyway. I would link it anyway for those lucky enough to understand german.
